openapi: 3.0.4
info:
  title: Tutorial API
  description: API for managing users and tutorials with authentication using Bearer Token.
  version: 1.0.12
  servers:
  - url: http://localhost:8080/api
  